
server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  output:
    ansi:
      enabled: always
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: insta
    password: 15ndaq
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true  
      hibernate.format_sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  security:
    user:
      name: test
      password: 1234

logging:
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.cos.instagram: info
    com.cos.instagram.controller: debug 
      
#file:
#  path: C:/Users/ckdgh/git/SpringBoot/instagram/src/main/resources/static/upload/
  
custom:
  path:
    upload-images: 'C:/src/springboot/insta/'


